### PR TITLE
Update signup client side validation

### PR DESCRIPTION
**Pull request by relaxwenj**

### CODE REVIEW

**Review by ZhangTerrence — COMMENTED** [review]
Can you add the regex check for password as well? Also, right now the password validation only checks for alphanumeric characters, so can you update the user validation functions to check for what we put in the specs?

**Comment by ZhangTerrence** [comment]
On a similar note, since the user validation functions aren't updated, the user is able to update their username to include non-alphanumeric characters even though that shouldn't be allowed according to the specs.

**Comment by ZhangTerrence** [comment]
So basically, we still have to update all of the server-side and client-side user validations.

**Comment by relaxwenj** [comment]
I will update the user's server-side validation later today, and then I will modify the client-side accordingly.

**Review by ZhangTerrence — APPROVED** [review]

**Pull request merged**
